name: 21CMMC_dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numpy
  - scipy
  - astropy
  - scikit-learn
  - matplotlib
  - cxx-compiler
  - fftw
  - cffi
  - gsl
  - pyyaml
  - click
  - openmp
  - h5py
  - emcee=2
  - corner
  - ipykernel
  - pip:
    - tox
    - pylint
    - black
    - pytest
    - pre-commit
